package com.mdad.windows;

/*
 * <p> Descripción: Interfaz principal <p>
 * @author Gloria Díaz
 * @version 02/06/2021 - V1.0
 */
import com.mdad.spotifylist.Operations;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;


/**
 * Clase que contiene la ventana inicial del programa
 */
public class Interface extends javax.swing.JFrame {

    //Fuciones
    Operations op = new Operations();
    
    //Ventanas
    MoreInfo IMoreInfo = new MoreInfo();
    ConsultData IConsultData = new ConsultData();
    InsertData IInsertData = new InsertData();

    /**
     * Creates new form Interface
     */
    public Interface() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        this.setTitle("Gestión de Spotify");
        
        op.createKeySpace();
        op.createTable();
        
        areaDeTexto.append("Funcionamiento:\n    1º Selecciona los datos según la consulta que vaya a realizar.\n    2º Ejecuta la consulta deseada.\n\n");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jScrollPane1 = new javax.swing.JScrollPane();
        areaDeTexto = new javax.swing.JTextArea();
        limpiar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        fichero = new javax.swing.JMenu();
        deleteTable = new javax.swing.JMenuItem();
        createTable = new javax.swing.JMenuItem();
        exit = new javax.swing.JMenuItem();
        opciones = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();
        selectInsert = new javax.swing.JMenuItem();
        selectConsult = new javax.swing.JMenuItem();
        selectUpdate = new javax.swing.JMenuItem();
        selectDelete = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        insert = new javax.swing.JMenuItem();
        consult = new javax.swing.JMenuItem();
        update = new javax.swing.JMenuItem();
        delete = new javax.swing.JMenuItem();
        ayuda = new javax.swing.JMenu();
        about = new javax.swing.JMenuItem();

        jMenuItem7.setText("jMenuItem7");

        jMenuItem2.setText("jMenuItem2");

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        areaDeTexto.setColumns(20);
        areaDeTexto.setRows(5);
        areaDeTexto.setWrapStyleWord(true);
        areaDeTexto.setAutoscrolls(false);
        jScrollPane1.setViewportView(areaDeTexto);

        limpiar.setText("Limpiar Consola");
        limpiar.setAlignmentX(0.5F);
        limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpiarActionPerformed(evt);
            }
        });

        jLabel1.setText("Console");

        jLabel2.setText("Result consult");

        fichero.setText("File");

        deleteTable.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        deleteTable.setText("Delete Table");
        deleteTable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteTableActionPerformed(evt);
            }
        });
        fichero.add(deleteTable);

        createTable.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        createTable.setText("Create Table");
        createTable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createTableActionPerformed(evt);
            }
        });
        fichero.add(createTable);

        exit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ESCAPE, 0));
        exit.setText("Exit");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        fichero.add(exit);

        jMenuBar1.add(fichero);

        opciones.setText("CRUD");

        jMenu1.setText("Select Data");

        selectInsert.setText("Insert");
        selectInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectInsertActionPerformed(evt);
            }
        });
        jMenu1.add(selectInsert);

        selectConsult.setText("Consult");
        selectConsult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectConsultActionPerformed(evt);
            }
        });
        jMenu1.add(selectConsult);

        selectUpdate.setText("Update");
        selectUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectUpdateActionPerformed(evt);
            }
        });
        jMenu1.add(selectUpdate);

        selectDelete.setText("Delete");
        selectDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectDeleteActionPerformed(evt);
            }
        });
        jMenu1.add(selectDelete);

        opciones.add(jMenu1);

        jMenu2.setText("Execute");

        insert.setText("Insert");
        insert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertActionPerformed(evt);
            }
        });
        jMenu2.add(insert);

        consult.setText("Consult");
        consult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultActionPerformed(evt);
            }
        });
        jMenu2.add(consult);

        update.setText("Update");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });
        jMenu2.add(update);

        delete.setText("Delete");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });
        jMenu2.add(delete);

        opciones.add(jMenu2);

        jMenuBar1.add(opciones);

        ayuda.setText("Help");

        about.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        about.setText("More Info");
        about.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutActionPerformed(evt);
            }
        });
        ayuda.add(about);

        jMenuBar1.add(ayuda);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1600, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(limpiar)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(7, 7, 7)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(limpiar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 484, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Boton limpiar
     */
    private void limpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpiarActionPerformed
        areaDeTexto.setText("");
    }//GEN-LAST:event_limpiarActionPerformed

    /**
     * Boton salir
     */
    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        op.cerrar();
        System.exit(1);
    }//GEN-LAST:event_exitActionPerformed

    /**
     * Boton acerca de
     */
    private void aboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutActionPerformed
        IMoreInfo.setVisible(true);
    }//GEN-LAST:event_aboutActionPerformed

    private void insertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertActionPerformed
        
        op.insertData(IInsertData.getInstertValues());
        
        areaDeTexto.append("INSERT:\n    La canción " + IInsertData.getInstertValues()[1] + " se ha insertado correctamente\n");
        
        IInsertData.resetConfig();
    }//GEN-LAST:event_insertActionPerformed

    private void consultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultActionPerformed
        String columnNames[];
        
            
        if(IConsultData.getValue().equals(" ") && !IConsultData.getAttribute().equals("all")){
            columnNames = new String[]{IConsultData.getAttribute()};
            
            areaDeTexto.append("SELECT:\n    Consulta de datos de la columna " + IConsultData.getAttribute().toUpperCase()+"\n");
        }
        else{
            if(IConsultData.getAttribute().equals("all"))                
                areaDeTexto.append("SELECT:\n    Consulta de TODOS los valores\n");
        
            else
                areaDeTexto.append("SELECT:\n    Consulta de la columna " + IConsultData.getAttribute().toUpperCase() + " con valor " + IConsultData.getValue().toUpperCase()+"\n");
        
            columnNames = new String[]{"Id", "Title" , "Artist", "Top genre", "Year", "BPM", "Energy", "Dance", "dB", "Live", "Valance", "Duration", "Acousticness", "Speechiness", "Popularity"};
        
        }
        
        Object[][] data = op.searchData(IConsultData.getAttribute(), IConsultData.getValue());
        
        while (data == null);
        
        DefaultTableModel dtm = new DefaultTableModel(data, columnNames);
        JTable DataTabla = new JTable ();
        
        DataTabla.setModel(dtm); 
        jScrollPane2.setViewportView(DataTabla);
        
        IConsultData.resetConfig();
    }//GEN-LAST:event_consultActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        op.updateData(IConsultData.getAttribute(), IConsultData.getValue(), IInsertData.getInstertValues());
        
        areaDeTexto.append("UPDATE:\n    La canción " + IInsertData.getInstertValues()[0] + " se ha actualizado correctamente\n");
        
        IInsertData.resetConfig();
        IConsultData.resetConfig();
    }//GEN-LAST:event_updateActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        op.deleteData(IConsultData.getAttribute(), IConsultData.getValue());
        
        areaDeTexto.append("DELETE:\n    Se ha eliminado el dato " + IConsultData.getValue() +"\n");
        
        IConsultData.resetConfig();
    }//GEN-LAST:event_deleteActionPerformed

    private void deleteTableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteTableActionPerformed
        op.deleteTable();
        
        areaDeTexto.append("  Se ha eliminado la tabla Songs\n\n");
    }//GEN-LAST:event_deleteTableActionPerformed

    private void createTableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createTableActionPerformed
        op.createTable();
        
        areaDeTexto.append("  Se ha creado la tabla Songs\n\n");
    }//GEN-LAST:event_createTableActionPerformed

    private void selectConsultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectConsultActionPerformed
        
        IConsultData.setLabelInterface("1. Select attribute", "2. Select attribute and write value");
        
        IConsultData.setVisible(true);
    }//GEN-LAST:event_selectConsultActionPerformed

    private void selectInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectInsertActionPerformed
                
        IInsertData.setVisible(true);
    }//GEN-LAST:event_selectInsertActionPerformed

    private void selectUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectUpdateActionPerformed
        
        IInsertData.setVisible(true);
                
        IConsultData.setLabelInterface("1. Select change by Id", "2. Select change by Title");
                
        IConsultData.setVisible(true);
    }//GEN-LAST:event_selectUpdateActionPerformed

    private void selectDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectDeleteActionPerformed
                
        IConsultData.setLabelInterface("1. Select delete by Id", "2. Select delete by Title");
        
        IConsultData.setVisible(true);
    }//GEN-LAST:event_selectDeleteActionPerformed

    public void InterInsertVisible(){
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem about;
    private javax.swing.JTextArea areaDeTexto;
    private javax.swing.JMenu ayuda;
    private javax.swing.JMenuItem consult;
    private javax.swing.JMenuItem createTable;
    private javax.swing.JMenuItem delete;
    private javax.swing.JMenuItem deleteTable;
    private javax.swing.JMenuItem exit;
    private javax.swing.JMenu fichero;
    private javax.swing.JMenuItem insert;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton limpiar;
    private javax.swing.JMenu opciones;
    private javax.swing.JMenuItem selectConsult;
    private javax.swing.JMenuItem selectDelete;
    private javax.swing.JMenuItem selectInsert;
    private javax.swing.JMenuItem selectUpdate;
    private javax.swing.JMenuItem update;
    // End of variables declaration//GEN-END:variables

}
